# Generated by Django 3.1.1 on 2025-11-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_create_room_and_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='credits',
            field=models.PositiveSmallIntegerField(default=0, help_text='Classes per week limit'),
        ),
    ]
