# Generated by Django 3.1.1 on 2025-11-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20251106_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='duration_periods',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='is_lab',
            field=models.BooleanField(default=False),
        ),
    ]
