# Generated by Django 3.1.1 on 2025-11-10

from django.db import migrations, models


def forwards_copy_course_to_courses(apps, schema_editor):
    Subject = apps.get_model('main_app', 'Subject')
    Course = apps.get_model('main_app', 'Course')
    for subj in Subject.objects.all():
        try:
            # Old FK field may exist during this step
            course = getattr(subj, 'course', None)
            if course:
                subj.courses.add(course)
        except Exception:
            # Ignore if no old field or other issues
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20251107_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='courses',
            field=models.ManyToManyField(related_name='subjects', to='main_app.Course'),
        ),
        migrations.RunPython(forwards_copy_course_to_courses, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='subject',
            name='course',
        ),
    ]