# Generated by Django 3.1.1 on 2025-11-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_allow_multiple_fee_submissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcqtest',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
