# Generated by Django 3.1.1 on 2025-11-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_mcqtest_scheduled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereportstudent',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='leave_attachments/'),
        ),
    ]
